### ISSUE TITLE
Pengumpulan Submission HTML Basic PCDB

### ISSUE THREAD

**Issue by not-xygen** [pmb-community/PDCB-Repository#1]
### Kumpulkan link repo dengan format

**Nama - NIM - Link Repo**
Cth: Dhaffa - 11201020 - https://github.com/pmb-community/PDCB-Repository/issues/new

Penilaian:
-  Struktur HTML
-  Implementasi Semantic HTML
-  Implementasi Form HTML
- Penyambungan CSS & JS

Notes:
- Untuk CSS bisa menggubah font, Improvisasi bisa tapi tidak dinilai
- Untuk JS implementasi pemanggilan fungsi saat submit form

Yang sudah menamatkan HTML ku kasih jempol kayak dibawah

**Comment by not-xygen** [comment]
Dhaffa - 11201020 - https://github.com/pmb-community/PDCB-Repository/issues/new

**Comment by not-xygen** [comment]
Dhaffa - 11201020 - https://github.com/not-xygen/pcdb-bootcamp

**Comment by nuralims** [comment]
Muhammad Nuralimsyah - 11211061 - https://github.com/KipasTerbang/Teras-Alim.git

**Comment by NARajab** [comment]
Nur Ali Rajab - 11211067 - https://github.com/NARajab/legobot.git

**Comment by not-xygen** [comment]
> Muhammad Nuralimsyah - 11211061 - https://github.com/KipasTerbang/Teras-Alim.git
> Nur Ali Rajab - 11211067 - https://github.com/NARajab/legobot.git

Cek issues repo kalian yah

**Comment by carolineadicahya** [comment]
Caroline Adi Cahya - 11211026 - https://github.com/carolineadicahya/bootcamp-pcmb

**Comment by Mahardika-23** [comment]
B.mahardika - 11211023 - https://github.com/MyNameIsJustD/JustD.git

**Comment by anisaaindraa** [comment]
Anisya Indra Wijaya - 11211014 - https://github.com/anisaaindraa/project1-pcmb.git

**Comment by fzhnf** [comment]
Faiz Ahnaf Samudra Azis - 11221076 - https://github.com/fzhnf/catppuccinWorld

**Comment by anisaaindraa** [comment]
> Anisya Indra Wijaya - 11211014 - https://github.com/anisaaindraa/project1-pcmb.git

Anisya Indra Wijaya - 11211014 - revisi - https://github.com/anisaaindraa/revisi-project1.git

**Comment by anisaaindraa** [comment]
Anisya Indra Wijaya -11211014 - https://github.com/anisaaindraa/revisi-project1.git

**Comment by reno99986** [comment]
Reno Fahrezi Purnomo - 11221051 https://github.com/reno99986/latihan_html.git

**Comment by dionp3** [comment]
Dion Prayoga - 11221058 - https://github.com/dionp3/PDCB-HTML-Basic-Project.git

**Comment by ihsaan15** [comment]
Muamnar Ihsan - 11221053 - https://github.com/beruanglaut115/skrrttt.git

**Comment by almaaaddara** [comment]
Almaditha Dara T - 11211008 - https://github.com/almaaaddara/bootcamppmb/tree/main/bootcmp

**Comment by Aozora09** [comment]
Azhari Rambe - 11221019 - https://github.com/Aozora09/newbyeee

**Comment by Chuu04** [comment]
Cinta Satilla - 11221071 - https://github.com/Chuu04/Proyek-Web-PCDB.git

**Comment by halannn** [comment]
Hairul Irawan - 11221043 - https://github.com/Halan401/PDCB-PMB.git

**Comment by TatakAdi** [comment]
Tatak Adi Subagyo - 11221073 - https://github.com/TatakAdi/Project1-PMB-Tatak-Adi-11221073

**Comment by desssti06** [comment]
Desti Nur Irawati - 11221033 - https://github.com/desssti06/project-web-dev-1

**Comment by kevin-nathaniel** [comment]
Jo Kevin Nathaniel - 11201046 - https://github.com/kevin-nathaniel/Basic-Web

**Comment by Wiraproject** [comment]
Wiranto - 11221030 - https://github.com/Wiraproject/FinalProject.git

**Comment by LailaMust** [comment]
Laila Mustika Sari - 11221002 - https://github.com/LailaMust/PDCB-Web-Dev.git

**Comment by Dillaayh** [comment]
Dilla Ayu Puspitasari_11221031_https://github.com/Dillaayh/dillaayu

**Comment by Yossiezraa** [comment]
Yossi Ezra Afriani_11211087_https://github.com/Yossiezraa/SubmissionHTML.git

**Comment by azureeeeeeeeeeee** [comment]
Rionando Soeksin Putra - 11221063 - https://github.com/Riooooo27/PDCB-PMB

**Comment by Fadil-Tao** [comment]
Hadad Fadilah - 11221029 - https://github.com/Fadil-Tao/Gabut

**Comment by Rellganss** [comment]
Darrell Timothy Nasarany - 11211029 - https://github.com/Rellganss/belajarbersamapmb.git

**Comment by Felix1180** [comment]
Christian Felix - 11221080 - https://github.com/Felix1180/TugasHTML.git

**Comment by Ayiais** [comment]
Alifah Nur Aisyah - Alifah Nur Aisyah - https://github.com/Ayiais/project1.git

**Comment by glenngladly26** [comment]
Glenn Gladly Gessong - 11221070 - https://github.com/glenngladly26/TugasPelatihanHTML.git

**Comment by iqbalfhrzii** [comment]
Iqbal Fahrozi - 11221034 - https://github.com/iqbalfhrzii/Project1

**Comment by Yunnifa** [comment]
Yunnifa Nur Lailli - 11221040 - https://github.com/Yunnifa/PDCB-WebProject/

**Comment by Mocfigh** [comment]
Arifia Dyah Sulistyani - 11221061 - https://github.com/Mocfigh/Projeck-WebDev-1.git

**Comment by rapliultraman** [comment]
Rafli Pratama Yuliandi - 11221090 - https://github.com/rapliultraman/BOOTCAMP-front-end.git

**Comment by Noufall90** [comment]
Naufal andrian - 11221075 - revisi - https://github.com/Noufall90/PROJECT-WEB

**Comment by glenngladly26** [comment]
Glenn Gladly Gessong - 11221070 - Revisi - https://github.com/glenngladly26/TugasPelatihanHTML.git

**Comment by zayfitri** [comment]
Isnaini Zayyana Fitri - 11221072 - https://github.com/zayfitri/project-html

**Comment by SyifaMaulida18** [comment]
Syifa Maulida - 11221007 - https://github.com/SyifaMaulida18/SyifaMaulida

**Comment by Abigailpormes** [comment]
Abigail Pormes - 11221048 - https://github.com/Abigailpormes/Secret_html.git

**Comment by a-yuu** [comment]
Ayu Nabila - 11221084 - https://github.com/a-yuu/PMB

**Comment by Yossiezraa** [comment]
Yossi Ezra Afriani-11211087-https://github.com/Yossiezraa/submitHTML.git
